const nationalityToFlagCode: Record<string, string> = {
  ALB: 'al',
  Albania: 'al',
  ALG: 'dz',
  Algeria: 'dz',
  ANG: 'ao',
  Angola: 'ao',
  ARG: 'ar',
  Argentina: 'ar',
  ARM: 'am',
  Armenia: 'am',
  AUS: 'au',
  Australia: 'au',
  AUT: 'at',
  Austria: 'at',
  BDI: 'bi',
  Burundi: 'bi',
  BEL: 'be',
  Belgium: 'be',
  BEN: 'bj',
  Benin: 'bj',
  BFA: 'bf',
  'Burkina Faso': 'bf',
  BIH: 'ba',
  'Bosnia and Herzegovina': 'ba',
  BRB: 'bb',
  Barbados: 'bb',
  BRA: 'br',
  Brazil: 'br',
  BUL: 'bg',
  Bulgaria: 'bg',
  CAN: 'ca',
  Canada: 'ca',
  CGO: 'cg',
  Congo: 'cg',
  CHI: 'cl',
  Chile: 'cl',
  CIV: 'ci',
  "CÃ´te d'Ivoire": 'ci',
  CMR: 'cm',
  Cameroon: 'cm',
  COD: 'cd',
  'DR Congo': 'cd',
  COL: 'co',
  Colombia: 'co',
  COM: 'km',
  Comoros: 'km',
  CRO: 'hr',
  Croatia: 'hr',
  CTA: 'cf',
  'Central African Republic': 'cf',
  CYP: 'cy',
  Cyprus: 'cy',
  CZE: 'cz',
  Czechia: 'cz',
  Czech: 'cz',
  DEN: 'dk',
  Denmark: 'dk',
  DOM: 'do',
  'Dominican Republic': 'do',
  ECU: 'ec',
  Ecuador: 'ec',
  EGY: 'eg',
  Egypt: 'eg',
  ENG: 'gb-eng',
  England: 'gb-eng',
  EQG: 'gq',
  'Equatorial Guinea': 'gq',
  ESP: 'es',
  Spain: 'es',
  EST: 'ee',
  Estonia: 'ee',
  FIN: 'fi',
  Finland: 'fi',
  FRA: 'fr',
  France: 'fr',
  FRO: 'fo',
  'Faroe Islands': 'fo',
  GAB: 'ga',
  Gabon: 'ga',
  GAM: 'gm',
  Gambia: 'gm',
  GEO: 'ge',
  Georgia: 'ge',
  GER: 'de',
  Germany: 'de',
  GHA: 'gh',
  Ghana: 'gh',
  GLP: 'gp',
  Guadeloupe: 'gp',
  GNB: 'gw',
  'Guinea-Bissau': 'gw',
  GRE: 'gr',
  Greece: 'gr',
  GUF: 'gf',
  'French Guiana': 'gf',
  GUI: 'gn',
  Guinea: 'gn',
  HAI: 'ht',
  Haiti: 'ht',
  HON: 'hn',
  Honduras: 'hn',
  HUN: 'hu',
  Hungary: 'hu',
  IDN: 'id',
  Indonesia: 'id',
  IRL: 'ie',
  Ireland: 'ie',
  ISL: 'is',
  Iceland: 'is',
  ISR: 'il',
  Israel: 'il',
  ITA: 'it',
  Italy: 'it',
  JAM: 'jm',
  Jamaica: 'jm',
  JOR: 'jo',
  Jordan: 'jo',
  JPN: 'jp',
  Japan: 'jp',
  KEN: 'ke',
  Kenya: 'ke',
  KOR: 'kr',
  'South Korea': 'kr',
  KSA: 'sa',
  'Saudi Arabia': 'sa',
  KVX: 'xk',
  Kosovo: 'xk',
  LBY: 'ly',
  Libya: 'ly',
  LTU: 'lt',
  Lithuania: 'lt',
  LUX: 'lu',
  Luxembourg: 'lu',
  MAD: 'mg',
  Madagascar: 'mg',
  MAS: 'my',
  Malaysia: 'my',
  MEX: 'mx',
  Mexico: 'mx',
  MKD: 'mk',
  'North Macedonia': 'mk',
  MLI: 'ml',
  Mali: 'ml',
  MNE: 'me',
  Montenegro: 'me',
  MAR: 'ma',
  Morocco: 'ma',
  MOZ: 'mz',
  Mozambique: 'mz',
  MTN: 'mr',
  Mauritania: 'mr',
  MTQ: 'mq',
  Martinique: 'mq',
  NED: 'nl',
  Netherlands: 'nl',
  NGA: 'ng',
  Nigeria: 'ng',
  NIG: 'ne',
  Niger: 'ne',
  NIR: 'gb-nir',
  'Northern Ireland': 'gb-nir',
  NOR: 'no',
  Norway: 'no',
  NZL: 'nz',
  'New Zealand': 'nz',
  PAN: 'pa',
  Panama: 'pa',
  PAR: 'py',
  Paraguay: 'py',
  PER: 'pe',
  Peru: 'pe',
  POL: 'pl',
  Poland: 'pl',
  POR: 'pt',
  Portugal: 'pt',
  RSA: 'za',
  'South Africa': 'za',
  ROU: 'ro',
  Romania: 'ro',
  RUS: 'ru',
  Russia: 'ru',
  SCO: 'gb-sct',
  Scotland: 'gb-sct',
  SEN: 'sn',
  Senegal: 'sn',
  SLE: 'sl',
  'Sierra Leone': 'sl',
  SRB: 'rs',
  Serbia: 'rs',
  SUR: 'sr',
  Suriname: 'sr',
  SVK: 'sk',
  SVKc: 'sk',
  Slovakia: 'sk',
  SUI: 'ch',
  Switzerland: 'ch',
  SVN: 'si',
  Slovenia: 'si',
  SWE: 'se',
  Sweden: 'se',
  TAN: 'tz',
  Tanzania: 'tz',
  THA: 'th',
  Thailand: 'th',
  TOG: 'tg',
  Togo: 'tg',
  TUN: 'tn',
  Tunisia: 'tn',
  TUR: 'tr',
  Turkey: 'tr',
  UKR: 'ua',
  Ukraine: 'ua',
  URU: 'uy',
  Uruguay: 'uy',
  USA: 'us',
  UZB: 'uz',
  Uzbekistan: 'uz',
  VEN: 've',
  Venezuela: 've',
  WAL: 'gb-wls',
  Wales: 'gb-wls',
  ZAM: 'zm',
  Zambia: 'zm',
  ZIM: 'zw',
  Zimbabwe: 'zw',
};

const nationalityToLabel: Record<string, string> = {
  ALB: 'Albanais',
  Albania: 'Albanais',
  ALG: 'Algerien',
  Algeria: 'Algerien',
  ANG: 'Angolais',
  Angola: 'Angolais',
  ARG: 'Argentin',
  Argentina: 'Argentin',
  ARM: 'Armenien',
  Armenia: 'Armenien',
  AUS: 'Australien',
  Australia: 'Australien',
  AUT: 'Autrichien',
  Austria: 'Autrichien',
  BDI: 'Burundais',
  Burundi: 'Burundais',
  BEL: 'Belge',
  Belgium: 'Belge',
  BEN: 'Beninois',
  Benin: 'Beninois',
  BFA: 'Burkinabe',
  'Burkina Faso': 'Burkinabe',
  BIH: 'Bosnien',
  'Bosnia and Herzegovina': 'Bosnien',
  BRB: 'Barbadien',
  Barbados: 'Barbadien',
  BRA: 'Bresilien',
  Brazil: 'Bresilien',
  BUL: 'Bulgare',
  Bulgaria: 'Bulgare',
  CAN: 'Canadien',
  Canada: 'Canadien',
  CGO: 'Congolais',
  Congo: 'Congolais',
  CHI: 'Chilien',
  Chile: 'Chilien',
  CIV: 'Ivoirien',
  "CÃ´te d'Ivoire": 'Ivoirien',
  CMR: 'Camerounais',
  Cameroon: 'Camerounais',
  COD: 'Congolais',
  'DR Congo': 'Congolais',
  COL: 'Colombien',
  Colombia: 'Colombien',
  COM: 'Comorien',
  Comoros: 'Comorien',
  CRO: 'Croate',
  Croatia: 'Croate',
  CTA: 'Centrafricain',
  'Central African Republic': 'Centrafricain',
  CYP: 'Chypriote',
  Cyprus: 'Chypriote',
  CZE: 'Tcheque',
  Czechia: 'Tcheque',
  Czech: 'Tcheque',
  DEN: 'Danois',
  Denmark: 'Danois',
  DOM: 'Dominicain',
  'Dominican Republic': 'Dominicain',
  ECU: 'Equatorien',
  Ecuador: 'Equatorien',
  EGY: 'Egyptien',
  Egypt: 'Egyptien',
  ENG: 'Anglais',
  England: 'Anglais',
  EQG: 'Equato-Guineen',
  'Equatorial Guinea': 'Equato-Guineen',
  ESP: 'Espagnol',
  Spain: 'Espagnol',
  EST: 'Estonien',
  Estonia: 'Estonien',
  FIN: 'Finlandais',
  Finland: 'Finlandais',
  FRA: 'Francais',
  France: 'Francais',
  FRO: 'Feroien',
  'Faroe Islands': 'Feroien',
  GAB: 'Gabonais',
  Gabon: 'Gabonais',
  GAM: 'Gambien',
  Gambia: 'Gambien',
  GEO: 'Georgien',
  Georgia: 'Georgien',
  GER: 'Allemand',
  Germany: 'Allemand',
  GHA: 'Ghaneen',
  Ghana: 'Ghaneen',
  GLP: 'Guadeloupeen',
  Guadeloupe: 'Guadeloupeen',
  GNB: 'Bissau-Guineen',
  'Guinea-Bissau': 'Bissau-Guineen',
  GRE: 'Grec',
  Greece: 'Grec',
  GUF: 'Guyanais',
  'French Guiana': 'Guyanais',
  GUI: 'Guineen',
  Guinea: 'Guineen',
  HAI: 'Haitien',
  Haiti: 'Haitien',
  HON: 'Hondurien',
  Honduras: 'Hondurien',
  HUN: 'Hongrois',
  Hungary: 'Hongrois',
  IDN: 'Indonesien',
  Indonesia: 'Indonesien',
  IRL: 'Irlandais',
  Ireland: 'Irlandais',
  ISL: 'Islandais',
  Iceland: 'Islandais',
  ISR: 'Israelien',
  Israel: 'Israelien',
  ITA: 'Italien',
  Italy: 'Italien',
  JAM: 'Jamaicain',
  Jamaica: 'Jamaicain',
  JOR: 'Jordanien',
  Jordan: 'Jordanien',
  JPN: 'Japonais',
  Japan: 'Japonais',
  KEN: 'Kenyan',
  Kenya: 'Kenyan',
  KOR: 'Sudo-Coreen',
  'South Korea': 'Sudo-Coreen',
  KSA: 'Saoudien',
  'Saudi Arabia': 'Saoudien',
  KVX: 'Kosovar',
  Kosovo: 'Kosovar',
  LBY: 'Libyen',
  Libya: 'Libyen',
  LTU: 'Lituanien',
  Lithuania: 'Lituanien',
  LUX: 'Luxembourgeois',
  Luxembourg: 'Luxembourgeois',
  MAD: 'Malgache',
  Madagascar: 'Malgache',
  MAR: 'Marocain',
  Morocco: 'Marocain',
  MAS: 'Malaisien',
  Malaysia: 'Malaisien',
  MEX: 'Mexicain',
  Mexico: 'Mexicain',
  MKD: 'Macedonien',
  'North Macedonia': 'Macedonien',
  MLI: 'Malien',
  Mali: 'Malien',
  MNE: 'Montenegrin',
  Montenegro: 'Montenegrin',
  MOZ: 'Mozambicain',
  Mozambique: 'Mozambicain',
  MTN: 'Mauritanien',
  Mauritania: 'Mauritanien',
  MTQ: 'Martiniquais',
  Martinique: 'Martiniquais',
  NED: 'Neerlandais',
  Netherlands: 'Neerlandais',
  NGA: 'Nigerian',
  Nigeria: 'Nigerian',
  NIG: 'Nigerien',
  Niger: 'Nigerien',
  NIR: 'Nord-Irlandais',
  'Northern Ireland': 'Nord-Irlandais',
  NOR: 'Norvegien',
  Norway: 'Norvegien',
  NZL: 'Neozelandais',
  'New Zealand': 'Neozelandais',
  PAN: 'Panameen',
  Panama: 'Panameen',
  PAR: 'Paraguayen',
  Paraguay: 'Paraguayen',
  PER: 'Peruvien',
  Peru: 'Peruvien',
  POL: 'Polonais',
  Poland: 'Polonais',
  POR: 'Portugais',
  Portugal: 'Portugais',
  RSA: 'Sud-Africain',
  'South Africa': 'Sud-Africain',
  ROU: 'Roumain',
  Romania: 'Roumain',
  RUS: 'Russe',
  Russia: 'Russe',
  SCO: 'Ecossais',
  Scotland: 'Ecossais',
  SEN: 'Senegalais',
  Senegal: 'Senegalais',
  SLE: 'Sierra-Leonais',
  'Sierra Leone': 'Sierra-Leonais',
  SRB: 'Serbe',
  Serbia: 'Serbe',
  SUR: 'Surinamais',
  Suriname: 'Surinamais',
  SVK: 'Slovaque',
  SVKc: 'Slovaque',
  Slovakia: 'Slovaque',
  SUI: 'Suisse',
  Switzerland: 'Suisse',
  SVN: 'Slovene',
  Slovenia: 'Slovene',
  SWE: 'Suedois',
  Sweden: 'Suedois',
  TAN: 'Tanzanien',
  Tanzania: 'Tanzanien',
  THA: 'Thailandais',
  Thailand: 'Thailandais',
  TOG: 'Togolais',
  Togo: 'Togolais',
  TUN: 'Tunisien',
  Tunisia: 'Tunisien',
  TUR: 'Turc',
  Turkey: 'Turc',
  UKR: 'Ukrainien',
  Ukraine: 'Ukrainien',
  URU: 'Uruguayen',
  Uruguay: 'Uruguayen',
  USA: 'Americain',
  UZB: 'Ouzbek',
  Uzbekistan: 'Ouzbek',
  VEN: 'Venezuelien',
  Venezuela: 'Venezuelien',
  WAL: 'Gallois',
  Wales: 'Gallois',
  ZAM: 'Zambien',
  Zambia: 'Zambien',
  ZIM: 'Zimbabween',
  Zimbabwe: 'Zimbabween',
};

export function getNationalityLabel(nationality: string) {
  return nationalityToLabel[nationality] ?? nationality;
}

export function getNationalityFlagCode(nationality: string) {
  return nationalityToFlagCode[nationality] ?? null;
}

export function formatLeagueLabel(league: string) {
  return league.replace(/^[a-z]{2,3}\s+/i, '');
}

export function formatTeamValue(totalValue: number) {
  return `${totalValue} MEUR`;
}

export function formatPlayerCount(count: number) {
  return `${count} joueur${count > 1 ? 's' : ''}`;
}
