const nationalityToFlagCode: Record<string, string> = {
  ALB: 'al',
  Albania: 'al',
  ALG: 'dz',
  Algeria: 'dz',
  ANG: 'ao',
  Angola: 'ao',
  ARG: 'ar',
  Argentina: 'ar',
  ARM: 'am',
  Armenia: 'am',
  AUS: 'au',
  Australia: 'au',
  AUT: 'at',
  Austria: 'at',
  BDI: 'bi',
  Burundi: 'bi',
  BEL: 'be',
  Belgium: 'be',
  BEN: 'bj',
  Benin: 'bj',
  BFA: 'bf',
  'Burkina Faso': 'bf',
  BIH: 'ba',
  'Bosnia and Herzegovina': 'ba',
  BRB: 'bb',
  Barbados: 'bb',
  BRA: 'br',
  Brazil: 'br',
  BUL: 'bg',
  Bulgaria: 'bg',
  CAN: 'ca',
  Canada: 'ca',
  CGO: 'cg',
  Congo: 'cg',
  CHI: 'cl',
  Chile: 'cl',
  CIV: 'ci',
  "Côte d'Ivoire": 'ci',
  CMR: 'cm',
  Cameroon: 'cm',
  COD: 'cd',
  'DR Congo': 'cd',
  COL: 'co',
  Colombia: 'co',
  COM: 'km',
  Comoros: 'km',
  CRO: 'hr',
  Croatia: 'hr',
  CTA: 'cf',
  'Central African Republic': 'cf',
  CYP: 'cy',
  Cyprus: 'cy',
  CZE: 'cz',
  Czechia: 'cz',
  Czech: 'cz',
  DEN: 'dk',
  Denmark: 'dk',
  DOM: 'do',
  'Dominican Republic': 'do',
  ECU: 'ec',
  Ecuador: 'ec',
  EGY: 'eg',
  Egypt: 'eg',
  ENG: 'gb-eng',
  England: 'gb-eng',
  EQG: 'gq',
  'Equatorial Guinea': 'gq',
  ESP: 'es',
  Spain: 'es',
  EST: 'ee',
  Estonia: 'ee',
  FIN: 'fi',
  Finland: 'fi',
  FRA: 'fr',
  France: 'fr',
  FRO: 'fo',
  'Faroe Islands': 'fo',
  GAB: 'ga',
  Gabon: 'ga',
  GAM: 'gm',
  Gambia: 'gm',
  GEO: 'ge',
  Georgia: 'ge',
  GER: 'de',
  Germany: 'de',
  GHA: 'gh',
  Ghana: 'gh',
  GLP: 'gp',
  Guadeloupe: 'gp',
  GNB: 'gw',
  'Guinea-Bissau': 'gw',
  GRE: 'gr',
  Greece: 'gr',
  GUF: 'gf',
  'French Guiana': 'gf',
  GUI: 'gn',
  Guinea: 'gn',
  HAI: 'ht',
  Haiti: 'ht',
  HON: 'hn',
  Honduras: 'hn',
  HUN: 'hu',
  Hungary: 'hu',
  IDN: 'id',
  Indonesia: 'id',
  IRL: 'ie',
  Ireland: 'ie',
  ISL: 'is',
  Iceland: 'is',
  ISR: 'il',
  Israel: 'il',
  ITA: 'it',
  Italy: 'it',
  JAM: 'jm',
  Jamaica: 'jm',
  JOR: 'jo',
  Jordan: 'jo',
  JPN: 'jp',
  Japan: 'jp',
  KEN: 'ke',
  Kenya: 'ke',
  KOR: 'kr',
  'South Korea': 'kr',
  KSA: 'sa',
  'Saudi Arabia': 'sa',
  KVX: 'xk',
  Kosovo: 'xk',
  LBY: 'ly',
  Libya: 'ly',
  LTU: 'lt',
  Lithuania: 'lt',
  LUX: 'lu',
  Luxembourg: 'lu',
  MAD: 'mg',
  Madagascar: 'mg',
  MAS: 'my',
  Malaysia: 'my',
  MEX: 'mx',
  Mexico: 'mx',
  MKD: 'mk',
  'North Macedonia': 'mk',
  MLI: 'ml',
  Mali: 'ml',
  MNE: 'me',
  Montenegro: 'me',
  MAR: 'ma',
  Morocco: 'ma',
  MOZ: 'mz',
  Mozambique: 'mz',
  MTN: 'mr',
  Mauritania: 'mr',
  MTQ: 'mq',
  Martinique: 'mq',
  NED: 'nl',
  Netherlands: 'nl',
  NGA: 'ng',
  Nigeria: 'ng',
  NIG: 'ne',
  Niger: 'ne',
  NIR: 'gb-nir',
  'Northern Ireland': 'gb-nir',
  NOR: 'no',
  Norway: 'no',
  NZL: 'nz',
  'New Zealand': 'nz',
  PAN: 'pa',
  Panama: 'pa',
  PAR: 'py',
  Paraguay: 'py',
  PER: 'pe',
  Peru: 'pe',
  POL: 'pl',
  Poland: 'pl',
  POR: 'pt',
  Portugal: 'pt',
  RSA: 'za',
  'South Africa': 'za',
  ROU: 'ro',
  Romania: 'ro',
  RUS: 'ru',
  Russia: 'ru',
  SCO: 'gb-sct',
  Scotland: 'gb-sct',
  SEN: 'sn',
  Senegal: 'sn',
  SLE: 'sl',
  'Sierra Leone': 'sl',
  SRB: 'rs',
  Serbia: 'rs',
  SUR: 'sr',
  Suriname: 'sr',
  SVK: 'sk',
  SVKc: 'sk',
  Slovakia: 'sk',
  SUI: 'ch',
  Switzerland: 'ch',
  SVN: 'si',
  Slovenia: 'si',
  SWE: 'se',
  Sweden: 'se',
  TAN: 'tz',
  Tanzania: 'tz',
  THA: 'th',
  Thailand: 'th',
  TOG: 'tg',
  Togo: 'tg',
  TUN: 'tn',
  Tunisia: 'tn',
  TUR: 'tr',
  Turkey: 'tr',
  UKR: 'ua',
  Ukraine: 'ua',
  URU: 'uy',
  Uruguay: 'uy',
  USA: 'us',
  UZB: 'uz',
  Uzbekistan: 'uz',
  VEN: 've',
  Venezuela: 've',
  WAL: 'gb-wls',
  Wales: 'gb-wls',
  ZAM: 'zm',
  Zambia: 'zm',
  ZIM: 'zw',
  Zimbabwe: 'zw',
};

export function getNationalityLabel(nationality: string) {
  return nationality;
}

export function getNationalityFlagCode(nationality: string) {
  return nationalityToFlagCode[nationality] ?? null;
}

export function formatTeamValue(totalValue: number) {
  return `${totalValue} MEUR`;
}

export function formatPlayerCount(count: number) {
  return `${count} joueur${count > 1 ? 's' : ''}`;
}
